name: Call Git Hub Action
on: 
  push:
    branches: [main]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:
    
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: runown container
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: "jai mata di"
          
      - name: Output time from contianer
        run: echo "time from container is  ${{ steps.hello-action.outputs.time}} when the action said anything"
        
      
        
      
    
